### PR TITLE
fix: Make smoddit work for bytesN map keys

### LINKED ISSUE #35: Setting a mapping bytes5 key fails
Hi! I'm using `smoddit` to set a mapping state with a bytes5 as key.

```solidity
pragma solidity ^0.8.0;

contract TestContract {
    
    mapping (bytes5 => bool) private mymapping;

    function setMyMapping(bytes5 _key, bool value) external {
        mymapping[_key] = value;
    }

    function getMyMapping(bytes5 _key) external view returns (bool _out) {
        return mymapping[_key];
    }
}
```

I expect both these tests to return true, but the second returns false.
```ts
import {ModifiableContract, ModifiableContractFactory, smoddit} from '@eth-optimism/smock';

describe('TestContract', () => {
    let contract: ModifiableContract;
    let factory: ModifiableContractFactory;

    describe('getMyMapping()', () => {
        before(async () => {
            factory = await smoddit('TestContract');
        });

        beforeEach(async () => {
            contract = await factory.deploy();
        });

        it('should return true', async () => {
            const key = '0x0000001234';
            await contract.setMyMapping(key, true);
            console.log(await contract.getMyMapping(key));
        });

        it('should return true', async () => {
            const key = '0x0000005678';
            contract.smodify.put({
                mymapping: {
                    [key]: true,
                },
            });
            console.log(await contract.getMyMapping(key));
        });
    });
});
```

Am I doing this right or messing up the bytes5 conversion?

**System Specs:**
- OS: Win10
- Engine: node v12.18.2
 - Package Version: @eth-optimism/smock@1.0.0-alpha.4

Thank you

### PR DESCRIPTION
**Pull request by smartcontracts**
**Description**
Fixes `smoddit` so that it'll work for `bytesN` keys. Underlying bug was that all values were being treated like `uint` and were being right-aligned (padding the start with zeros). Solidity handles `bytesN` where `N < 32` by padding the *end* with zeros (left-aligned). Also adds a regression test.

**Metadata**
- Fixes #35

### CODE REVIEW

File: src/utils/hex-utils.ts [hunk 1]
```diff
@@ -6,10 +6,15 @@ export const toHexString32 = (
   value: string | number | BigNumber | boolean
 ): string => {
   if (typeof value === 'string' && value.startsWith('0x')) {
-    return '0x' + remove0x(value).padStart(64, '0').toLowerCase()
```
Comment (smartcontracts) [inline src/utils/hex-utils.ts:9]: This function probably needs to be cleaned up in the future but whatever for now.

**Review by ben-chain — APPROVED** [review]
LGTM!
