### PR TITLE
fix: don't throw an error when a smocked fn has no calls

### LINKED ISSUE #42: TypeError when reading an empty calls array
I wanted to test that under a certain condition, no call is made to a contract. Using smock I would do something like:

expect(Mock__OVM_L2ToL1MessagePasser.smocked.sendMessage.calls.length).to.deep.equal(0)

That results in the same error in the above description (`TypeError: Cannot read property 'map' of undefined`). If it helps for context, here is what I wrote instead.

### PR DESCRIPTION
**Pull request by smartcontracts**
**Description**
Minor tweak to fix an error that causes smock to complain if you try to access calls for a function that hasn't been called yet.

**Metadata**
- Fixes #42

### CODE REVIEW

File: src/smockit/smockit.ts [hunk 1]
```diff
@@ -63,7 +63,7 @@ const smockifyFunction = (
       return
     },
     get calls() {
-      return vm._smockState.calls[contract.address.toLowerCase()]
+      return (vm._smockState.calls[contract.address.toLowerCase()] || [])
```
Comment (maurelian) [inline src/smockit/smockit.ts:66]: Nice. :)

Comment (smartcontracts) [reply src/smockit/smockit.ts:66]: ez pz!
